### ISSUE TITLE
Gravity Rush 2 not launching on Steam Deck

### ISSUE THREAD

**Issue by BenStringer3** [kalaposfos13/shadPS4#5]
Running shadps4-linux-sdl-2024-12-16-7c259ac on a steam deck gives graphical glitches and then closes.

[gr2-logds.log](https://github.com/user-attachments/files/18181073/gr2-logds.log)

**Comment by kalaposfos13** [comment]
Fortunately for you, the problem is quite simple: You don't have your system modules in sys_modules. You need the following files for it to boot:
libSceFiber.sprx
libSceLibcInternal.sprx

You also need these ones for text to show up:
libSceFont.sprx
libSceFontFt.sprx
libSceFreeTypeOt.sprx

And this one for (very broken, but better than nothing) sound:
libSceNgs2.sprx

Following [this](https://github.com/shadps4-emu/shadps4-game-compatibility?tab=readme-ov-file#info), I won't provide any support for getting these files from your PS4 to the emulator, because I don't want to risk getting banned, but there are some online guides you can follow.
